"""initial_schema

Revision ID: 6b97abb93b8a
Revises: 
Create Date: 2026-07-08 15:20:31.214458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b97abb93b8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('airports',
    sa.Column('airport_id', sa.Integer(), nullable=False),
    sa.Column('airport_code', sa.String(length=10), nullable=False),
    sa.Column('airport_name', sa.String(length=100), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('habitat_profile', sa.String(length=50), nullable=False),
    sa.Column('elevation', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('airport_id')
    )
    op.create_index(op.f('ix_airports_airport_code'), 'airports', ['airport_code'], unique=True)
    op.create_index(op.f('ix_airports_airport_id'), 'airports', ['airport_id'], unique=False)
    op.create_table('model_metrics',
    sa.Column('metric_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('precision', sa.Float(), nullable=True),
    sa.Column('recall', sa.Float(), nullable=True),
    sa.Column('f1_score', sa.Float(), nullable=True),
    sa.Column('pr_auc', sa.Float(), nullable=True),
    sa.Column('evaluation_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('metric_id')
    )
    op.create_index(op.f('ix_model_metrics_metric_id'), 'model_metrics', ['metric_id'], unique=False)
    op.create_table('prediction_windows',
    sa.Column('window_id', sa.Integer(), nullable=False),
    sa.Column('airport_id', sa.Integer(), nullable=False),
    sa.Column('window_start', sa.DateTime(), nullable=False),
    sa.Column('window_end', sa.DateTime(), nullable=False),
    sa.Column('predicted_probability', sa.Float(), nullable=False),
    sa.Column('risk_level', sa.String(length=10), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.airport_id'], ),
    sa.PrimaryKeyConstraint('window_id')
    )
    op.create_index(op.f('ix_prediction_windows_airport_id'), 'prediction_windows', ['airport_id'], unique=False)
    op.create_index(op.f('ix_prediction_windows_window_id'), 'prediction_windows', ['window_id'], unique=False)
    op.create_table('synthetic_strike_events',
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('airport_id', sa.Integer(), nullable=False),
    sa.Column('event_time', sa.DateTime(), nullable=False),
    sa.Column('strike_occurred', sa.Integer(), nullable=False),
    sa.Column('strike_probability', sa.Float(), nullable=True),
    sa.Column('f_season', sa.Float(), nullable=True),
    sa.Column('f_dawn_dusk', sa.Float(), nullable=True),
    sa.Column('f_weather', sa.Float(), nullable=True),
    sa.Column('f_base', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.airport_id'], ),
    sa.PrimaryKeyConstraint('event_id')
    )
    op.create_index(op.f('ix_synthetic_strike_events_airport_id'), 'synthetic_strike_events', ['airport_id'], unique=False)
    op.create_index(op.f('ix_synthetic_strike_events_event_id'), 'synthetic_strike_events', ['event_id'], unique=False)
    op.create_index(op.f('ix_synthetic_strike_events_event_time'), 'synthetic_strike_events', ['event_time'], unique=False)
    op.create_table('weather_snapshots',
    sa.Column('weather_id', sa.Integer(), nullable=False),
    sa.Column('airport_id', sa.Integer(), nullable=False),
    sa.Column('observation_time', sa.DateTime(), nullable=False),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('visibility', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('precipitation', sa.Float(), nullable=True),
    sa.Column('cloud_cover', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.airport_id'], ),
    sa.PrimaryKeyConstraint('weather_id')
    )
    op.create_index(op.f('ix_weather_snapshots_airport_id'), 'weather_snapshots', ['airport_id'], unique=False)
    op.create_index(op.f('ix_weather_snapshots_observation_time'), 'weather_snapshots', ['observation_time'], unique=False)
    op.create_index(op.f('ix_weather_snapshots_weather_id'), 'weather_snapshots', ['weather_id'], unique=False)
    op.create_table('dispatch_alerts',
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('airport_id', sa.Integer(), nullable=False),
    sa.Column('window_id', sa.Integer(), nullable=False),
    sa.Column('alert_message', sa.String(length=500), nullable=False),
    sa.Column('alert_level', sa.String(length=10), nullable=False),
    sa.Column('recommended_action', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['airport_id'], ['airports.airport_id'], ),
    sa.ForeignKeyConstraint(['window_id'], ['prediction_windows.window_id'], ),
    sa.PrimaryKeyConstraint('alert_id')
    )
    op.create_index(op.f('ix_dispatch_alerts_airport_id'), 'dispatch_alerts', ['airport_id'], unique=False)
    op.create_index(op.f('ix_dispatch_alerts_alert_id'), 'dispatch_alerts', ['alert_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_dispatch_alerts_alert_id'), table_name='dispatch_alerts')
    op.drop_index(op.f('ix_dispatch_alerts_airport_id'), table_name='dispatch_alerts')
    op.drop_table('dispatch_alerts')
    op.drop_index(op.f('ix_weather_snapshots_weather_id'), table_name='weather_snapshots')
    op.drop_index(op.f('ix_weather_snapshots_observation_time'), table_name='weather_snapshots')
    op.drop_index(op.f('ix_weather_snapshots_airport_id'), table_name='weather_snapshots')
    op.drop_table('weather_snapshots')
    op.drop_index(op.f('ix_synthetic_strike_events_event_time'), table_name='synthetic_strike_events')
    op.drop_index(op.f('ix_synthetic_strike_events_event_id'), table_name='synthetic_strike_events')
    op.drop_index(op.f('ix_synthetic_strike_events_airport_id'), table_name='synthetic_strike_events')
    op.drop_table('synthetic_strike_events')
    op.drop_index(op.f('ix_prediction_windows_window_id'), table_name='prediction_windows')
    op.drop_index(op.f('ix_prediction_windows_airport_id'), table_name='prediction_windows')
    op.drop_table('prediction_windows')
    op.drop_index(op.f('ix_model_metrics_metric_id'), table_name='model_metrics')
    op.drop_table('model_metrics')
    op.drop_index(op.f('ix_airports_airport_id'), table_name='airports')
    op.drop_index(op.f('ix_airports_airport_code'), table_name='airports')
    op.drop_table('airports')
    # ### end Alembic commands ###
